server:
  port: 8084

spring:
  application:
    name: mybs-log-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
        username: nacos
        password: nacos
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        namespace: public
        import-check:
          enabled: false
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: "123456"
      timeout: 3000ms

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: mybs
    username: mybs
    password: mybs
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        prefetch: 1
